[project]
name = 'aerosync-blockchain-module'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.audit-trail]
path = 'contracts/audit-trail.clar'
clarity_version = 3
epoch = 'latest'

[contracts.cargo-ledger]
path = 'contracts/cargo-ledger.clar'
clarity_version = 3
epoch = 'latest'

[contracts.flight-manifest]
path = 'contracts/flight-manifest.clar'
clarity_version = 3
epoch = 'latest'

[contracts.maintenance-log]
path = 'contracts/maintenance-log.clar'
clarity_version = 3
epoch = 'latest'

[contracts.payment-mirror]
path = 'contracts/payment-mirror.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
